export const classNames = [
  "Barbarian",
  "Bard",
  "Cleric",
  "Druid",
  "Fighter",
  "Monk",
  "Paladin",
  "Ranger",
  "Rogue",
  "Sorcerer",
  "Warlock",
  "Wizard",
];

export const speciesNames = [
  "Aasimar",
  "Dragonborn (Black)",
  "Dragonborn (Blue)",
  "Dragonborn (Brass)",
  "Dragonborn (Bronze)",
  "Dragonborn (Copper)",
  "Dragonborn (Gold)",
  "Dragonborn (Green)",
  "Dragonborn (Red)",
  "Dragonborn (Silver)",
  "Dragonborn (White)",
  "Dwarf",
  "Elf (Drow)",
  "Elf (High)",
  "Elf (Wood)",
  "Gnome (Forest)",
  "Gnome (Rock)",
  "Goliath (Cloud)",
  "Goliath (Fire)",
  "Goliath (Frost)",
  "Goliath (Hill)",
  "Goliath (Stone)",
  "Goliath (Storm)",
  "Halfling",
  "Human",
  "Orc",
  "Tiefling (Abyssal)",
  "Tiefling (Chthonic)",
  "Tiefling (Infernal)",
];
